services:
  mysqldb:
    container_name: mysql-db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: stockdb
      # MYSQL_USER: klu
      # MYSQL_PASSWORD: klu
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql   # volume added here

  backend:
    image: puneeth1079/docker-backend:latest
    container_name: stockspringboot
    ports:
      - "2025:2001"
    depends_on:
      - mysqldb
    restart: on-failure

  frontend:
    image: puneeth1079/docker-frontend:latest
    container_name: stockreact
    ports:
      - "3000:80"
    depends_on:
      - backend

# Declare volumes at the bottom
volumes:
  mysql-data: